---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: apps
  name: app-frontend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: app-frontend
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-frontend
    spec:
      containers:
        - image: public.ecr.aws/i8w3e9p0/frontend-letscodebyada:latest
          imagePullPolicy: Always
          name: app-frontend
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: apps
  name: service-frontend
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP
  selector:
    app.kubernetes.io/name: app-frontend
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: apps
  name: ingress-frontend
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: service-frontend
                port:
                  number: 80