---
apiVersion: v1
kind: Namespace
metadata:
  name: apps
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: apps
  name: app-backend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: app-backend
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-backend
    spec:
      containers:
        - image: public.ecr.aws/i8w3e9p0/backend-letscodebyada:latest
          imagePullPolicy: Always
          name: app-backend
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: database-secrets
---
apiVersion: v1
kind: Service
metadata:
  namespace: apps
  name: service-backend
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
  selector:
    app.kubernetes.io/name: app-backend
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: apps
  name: ingress-backend
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: service-backend
                port:
                  number: 80